name: stargan-v2
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - pytorch
  - vim
  - ffmpeg
  - torchvision
  - pip
  - pip:
      - pillow
      - scipy
      - tqdm
      - munch
      - opencv-python
      - scikit-image
      - ffmpeg-python
